---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-metrics-server-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.6.0

    args:
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-use-node-status-port
