---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tautulli
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lscr.io/linuxserver/tautulli
      tag: latest
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "tautulli.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tautulli.${INTERNAL_DOMAIN}"
          - secretName: tautulli-tls
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
