---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-v1
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
