---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m

  values:

    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.2.3
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.2.3
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.2.3
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1_20211210
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1_20211020
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v2_20210820

      csi:
        attacher:
          repository: longhornio/csi-attacher
          tag: v3.2.1
        provisioner:
          repository: longhornio/csi-provisioner
          tag: v2.1.2
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          tag: v2.3.0
        resizer:
          repository: longhornio/csi-resizer
          tag: v1.2.0
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v3.0.3
      pullPolicy: IfNotPresent


    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.192.168.2.50.nip.io
      tls: false
      tlsSecret: longhorn.local-tls
