---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  maxHistory: 3
  interval: 1m0s
  suspend: false
  releaseName: istio-base
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istio-base
      version: 4.1.3
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
