---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  maxHistory: 3
  interval: 1m0s
  suspend: false
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.7.0
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  values:
    webhook:
      enabled: true
      securePort: 10666
    hostNetwork: true
