---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:

    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.715

    env:
      TZ: "America/New_York"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "readarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "readarr.${INTERNAL_DOMAIN}"
          - secretName: readarr-tls

    podSecurityContext:
      fsGroup: 0
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: readarr-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS3_ADDR}"
            path: /volume1/Books
        mountPath: /media
      temp:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/temp
        mountPath: /temp_dir

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
